// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9a2vkc1NaK8pgUCLc3BvEYMxuXgoHXTg',
    appId: '1:90758293891:web:1e36d768470d94e66caeb6',
    messagingSenderId: '90758293891',
    projectId: 'cash-agents',
    authDomain: 'cash-agents.firebaseapp.com',
    storageBucket: 'cash-agents.firebasestorage.app',
    measurementId: 'G-45R4DVRE7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPhZ3Dj2iju4iFpFPj6H3j84zwtGTVRRo',
    appId: '1:90758293891:android:553167ce1e00ea716caeb6',
    messagingSenderId: '90758293891',
    projectId: 'cash-agents',
    storageBucket: 'cash-agents.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgMu4goD-O0oClDXET4YPtOT8ulgCu6DI',
    appId: '1:90758293891:ios:8be6af0e594317466caeb6',
    messagingSenderId: '90758293891',
    projectId: 'cash-agents',
    storageBucket: 'cash-agents.firebasestorage.app',
    iosBundleId: 'com.example.cashAgentAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgMu4goD-O0oClDXET4YPtOT8ulgCu6DI',
    appId: '1:90758293891:ios:8be6af0e594317466caeb6',
    messagingSenderId: '90758293891',
    projectId: 'cash-agents',
    storageBucket: 'cash-agents.firebasestorage.app',
    iosBundleId: 'com.example.cashAgentAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9a2vkc1NaK8pgUCLc3BvEYMxuXgoHXTg',
    appId: '1:90758293891:web:1ccdeefe0902b8536caeb6',
    messagingSenderId: '90758293891',
    projectId: 'cash-agents',
    authDomain: 'cash-agents.firebaseapp.com',
    storageBucket: 'cash-agents.firebasestorage.app',
    measurementId: 'G-M2JWDY8K51',
  );
}
